# Generated by Django 4.2.16 on 2024-11-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='galeri_photos/')),
                ('deskripsi_singkat', models.TextField()),
                ('deskripsi_detail', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Galeri',
            },
        ),
    ]
