# Generated by Django 5.1.3 on 2024-11-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramsCompetitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('jenkel', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('tgl_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('pesan', models.TextField()),
                ('agree', models.BooleanField(default=False, verbose_name='Saya setuju untuk mengikuti lomba dan mengikuti syarat dan ketentuan yang berlaku')),
            ],
        ),
    ]
