# Generated by Django 5.1.3 on 2024-11-19 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programscompetitionmodel',
            name='waktu_kirim',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programscompetitionmodel',
            name='jenkel',
            field=models.CharField(choices=[('l', 'Laki-Laki'), ('p', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='programscompetitionmodel',
            name='tgl_lahir',
            field=models.DateField(verbose_name='Tanggal Lahir'),
        ),
    ]
