# Generated by Django 5.1.3 on 2024-11-20 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_programscompetitionmodel_waktu_kirim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programscompetitionmodel',
            name='waktu_kirim',
        ),
    ]
