# Generated by Django 5.1.2 on 2024-11-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_remove_programscompetitionmodel_waktu_kirim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('registration_status', models.CharField(choices=[('open', 'Daftar Sekarang'), ('limited', 'Tempat Terbatas'), ('closed', 'Pendaftaran Tutup')], default='open', max_length=20)),
            ],
            options={
                'verbose_name': 'Children Exhibition',
                'verbose_name_plural': 'Children Exhibitions',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CookingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=100)),
                ('ticket_status', models.CharField(choices=[('available', 'Tiket Tersedia'), ('limited', 'Tiket Hampir Habis'), ('sold_out', 'Tiket Habis Terjual')], default='available', max_length=20)),
            ],
            options={
                'verbose_name': 'Cooking Class',
                'verbose_name_plural': 'Cooking Classes',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ParentingSeminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('speaker', models.CharField(max_length=100)),
                ('ticket_status', models.CharField(choices=[('available', 'Tiket Tersedia'), ('limited', 'Tiket Hampir Habis'), ('sold_out', 'Tiket Habis Terjual')], default='available', max_length=20)),
            ],
            options={
                'verbose_name': 'Parenting Seminar',
                'verbose_name_plural': 'Parenting Seminars',
                'ordering': ['date'],
            },
        ),
    ]
