# Generated by Django 5.1.2 on 2024-11-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_childrenexhibition_cookingclass_parentingseminar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChildrenExhibition',
            new_name='ChildrenExhibitionModel',
        ),
        migrations.RenameModel(
            old_name='CookingClass',
            new_name='CookingClassModel',
        ),
        migrations.RenameModel(
            old_name='ParentingSeminar',
            new_name='ParentingSeminarModel',
        ),
    ]
