# Generated by Django 4.2.16 on 2024-12-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_program_teacher_schedule_fee_facility_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='description',
            field=models.TextField(default='Default description'),
        ),
    ]
