# Generated by Django 4.2.16 on 2024-12-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_facility_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='description',
            field=models.TextField(default='Default description'),
        ),
    ]
