# Generated by Django 4.2.16 on 2024-12-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_parentingseminarmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrenexhibitionmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='childrenexhibitionmodel',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='cookingclassmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cookingclassmodel',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='UserBooking',
        ),
    ]
